### ISSUE TITLE
help！my mcmctree doesn't work！

### ISSUE THREAD

**Issue by vincentkaiheng** [abacus-gene/paml#15]
When I use mcmctree to analyze the protein sequence, when I import in.BV, I get an error: error strange calibration. May I ask where is the problem? I have been modifying the tree file for several days.

**Comment by ziheng-yang** [comment]
"error strange calibration" means something is wrong with your calibration in the tree file.  for example if the age is between 6 and 8 myrs you should specify ">0.06<0.08", and you will get that error message if you specify "<0.06>0.08".
can you try the example in the examples/DateSoftBound folder and see whether the program runs.
ziheng

**Comment by vincentkaiheng** [comment]
Thank you very much!十分感谢杨教授！
