### ISSUE TITLE
tree file  not found.

### ISSUE THREAD

**Issue by lpipes** [abacus-gene/paml#18]
Hello,

I tried to use the example alignment `HIVenvSweden.txt` with the following control file `codeml.ctl`:
```
   seqfile = HIVenvSweden.txt
   outfile = results.out
    noisy = 0  
   verbose = 0  
   runmode = -2  
   seqtype = 1  
  CodonFreq = 2  
    model = 0
   NSsites = 0
```
And I get the following error with `codeml`
```
CODONML in paml version 4.10.5, March 2022

tree file  not found.
```

**Comment by ziheng-yang** [comment]
treefile = HIVenvSweden.trees   * tree structure file name

the control file codeml.ctl on github has the above line.  perhaps this was deleted by mistake?  you can add it bck and try again.
ziheng

**Comment by lpipes** [comment]
I am just testing these specific parameters on a control file. I thought for `runmode = -2` no control file is needed? This control file works for paml 4.9.

**Comment by ziheng-yang** [comment]
yes, you are right.  there should be no need for a species tree if runmode = -2, so that error check is wrong.
i'll edit the code to get this fixed.
ziheng
