### ISSUE TITLE
problems about "multiple NSsites models"

### ISSUE THREAD

**Issue by dll0408** [abacus-gene/paml#21]
Hi Professor:
   When I run multiple NSsites models in one go by specifying several models on the NSsites line in  codeml.ctl:  NSsites = 0 1 2 3 7 8, only the results of NSsites=0 was outputted, and revealed "# seqs in tree file does not match.  Read as the nexus format" in the screen. 
How can I run multiple NSsites models in one analysis? 
Thank you very much for your reading and replying!

**Comment by sabifo4** [comment]
Hi there!

Thanks for letting us know! This issue has now been resolved. More details about what the problem was and how it was addressed are available [in this other issue that reported the same problem](https://github.com/abacus-gene/paml/issues/30).
