### ISSUE TITLE
bump version number

### ISSUE THREAD

**Issue by jayoung** [abacus-gene/paml#22]
hi Ziheng,

I just stumbled on this git repo - nice!   

I downloaded v4.10.6.tar.gz  from the 'releases' section of the git repo just now, compiled it, and noticed that the version info is out of date when I run codeml.  I can see it is out of date in the `src/paml.h` file, too:
```
#define pamlVerStr "paml version 4.10.0, September 2020"
```

(the precompiled version doesn't work on my system, but I imagine that will show the wrong version info too)

all the best - hope you are well,

Janet

------------------------------------------------------------------- 

Dr. Janet Young 

Malik lab
http://research.fhcrc.org/malik/en.html

Division of Basic Sciences
Fred Hutchinson Cancer Center
1100 Fairview Avenue N., A2-025, 
P.O. Box 19024, Seattle, WA 98109-1024, USA.

tel: (206) 667 4512
email: jayoung  ...at...  fredhutch.org

-------------------------------------------------------------------

**Comment by sabifo4** [comment]
Hi Janet, 

Just wanted to let you know that this issue should be now fixed in the latest PAML release [`paml-4.10.7`](https://github.com/abacus-gene/paml/releases/tag/4.10.7).

Thanks for letting us know!
