### ISSUE TITLE
Linux packaging

### ISSUE THREAD

**Issue by V-Z** [abacus-gene/paml#24]
Not a issue, I just let You know that I'm packaging PAML for openSUSE at https://build.opensuse.org/package/show/home:vojtaeus/paml Everything works well, so thank You. :-)

**Comment by sabifo4** [comment]
Hi there!

As of today, you can download the latest PAML release, [`paml-4.10.7`](https://github.com/abacus-gene/paml/releases/tag/4.10.7), which fixes the last reported bugs in [this issue](https://github.com/abacus-gene/paml/issues/30). Please make sure that the latest version is also available via openSUSE :) 

Thanks!

**Comment by V-Z** [comment]
Done :-)
