### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by AJFeng** [abacus-gene/paml#25]
I have the 'segmentation fault' error for the 4.10 version. I can successfully run the ORF1b data, but have this error with ORF1a data. Total sequences are about 500, and same tree for the ORF1b data and  ORF1a data.

**Comment by sabifo4** [comment]
Hi there!

As of today, you can download a new PAML release available in which this problem should have been solved: [`paml-4.10.7`](https://github.com/abacus-gene/paml/releases/tag/4.10.7).

If you are using the cluster and you get this error, however, you may need to increase the amount of memory you are requesting -- perhaps your sequence alignment is quite large.

I am closing now this issue, thanks for letting us know!
