### ISSUE TITLE
CodeML Site model err

### ISSUE THREAD

**Issue by 32537** [abacus-gene/paml#26]
The err  is     Warning: Hessian matrix may be unreliable for zero branch lengths and then is killed.
I do not how to do it.
Thanks for your help!

**Comment by sabifo4** [comment]
Hi there, 

This issue was addressed on the PAML Google Group in 2019 (see [full discussion on the Google group](https://groups.google.com/g/pamlsoftware/c/bGyWBONFoh4/m/au4FunKdAgAJ)). Ziheng gave the following answer:

```text
this is a warning because some branch lengths are 0.  obviously if you have some identical sequences, some branch lengths will be 0.  i think you can ignore the warning.
```

Cheers!
