### ISSUE TITLE
# seqs in tree file does not match.  Read as the nexus format.

### ISSUE THREAD

**Issue by RetroWWU** [abacus-gene/paml#28]
Hello,
I figured out that paml 4.10.6 seems to behave differently than paml 4.9j  I got the error
# seqs in tree file does not match.  Read as the nexus format.
in 4.10 - but not i 4.9...  Is there a reason why?
Thanks - N. Grundmann
[AZI2.tre.txt](https://github.com/abacus-gene/paml/files/11650485/AZI2.tre.txt)
[AZI2_U.fasta.txt](https://github.com/abacus-gene/paml/files/11650486/AZI2_U.fasta.txt)
[codeml.ctl.txt](https://github.com/abacus-gene/paml/files/11650487/codeml.ctl.txt)

**Comment by sabifo4** [comment]
Hi there!

Thanks for letting us know! This issue has now been resolved. More details about what the problem was and how it was addressed are available [in this other issue that reported the same problem](https://github.com/abacus-gene/paml/issues/30).
