### ISSUE TITLE
Wrong version number output in 4.10.7 (mac)

### ISSUE THREAD

**Issue by bbitarello** [abacus-gene/paml#32]
Hello,
I noticed today that the 4.10.7 version for mac prints out that it's version 6. I also checked that this is so in the src/paml.h file:

`grep version paml.h
#define pamlVerStr "paml version 4.10.6, November 2022"`

I am assuming this is just a matter of fixing this message, but I wanted to bring it to your attention and also confirm that this version for mac is indeed 4.10.7?

Thank you

**Comment by sabifo4** [comment]
Hi there, 

Thanks for reporting! The version is indeed PAML v4.10.7, although the message printed might have not been updated. I will close this issue once we fix that.

Thanks!

**Comment by ziheng-yang** [comment]
i have just updated the release files for the mac.  there are 2 files, one for the intel chip, another for M1/M2.
hope they both work.
best wishes, 
ziheng
