### ISSUE TITLE
Error after update to 4.10.7

### ISSUE THREAD

**Issue by axeljen** [abacus-gene/paml#36]
Hi,

I've encountered an error in codeml after updating to 4.10.7, where the program runs almost to completion but then errors out with "error: end of tree file". The below example works fine in 4.9j, but not work with 4.10.7:

controlfile:
`seqfile = test_codeml_alignment.phy
outfile = test_codeml_null.out
treefile = test_codeml_tree.nwk
noisy = 3
verbose = 1
seqtype = 1
CodonFreq = 2
ndata = 1
clock = 0
model = 2
NSsites = 2
icode = 0
fix_omega = 1
omega = 1
cleandata = 0`

alignment:
`        6       87
sequence_1   ATGCAATCATATGCTTCTGCCATGTTAAGCGTATTTAACACTGATGGTTACAGTCCAGCTGCGCAACAGAATATTCCTGCTCTCCGG
sequence_2   ATGCAATCATATGCTTCTGCCATGTTAAGCGTATTTAACACTGATGGTTACAGTCCAGCTGCGCAACAGAATATTCCTGCTCTCCGG
sequence_3   ATGCAATCATATGCTTCTGCCATGTTAAGCGTGTTTAACACTGATGGTTACAGTCCAGCTGCGCAACAGCATATTCCTGCTCTCCGG
sequence_4   ATGCAATCATATGCTTCTGCCATGTTAAGCGTATTTAACACTGATGGTTACAGTCCAGCTGCGCAACAGAATATTCCTGCTCTCCGG
sequence_5   ATGCAATCATATGCTTCTGCCATGTTAAGCGTATTTAACACTGATGGTTACAGTCCAGCTGCGCAACAGAATATTCCTGCTCTCCGG
sequence_6   ATGCAATCATATGCTTCTGCCATGTTAAGCGTATTTAACACTGATGGTTACAGTCCAGCTGCGCAACAGAATATTCCTGCTCTCCGG`

tree:
`(sequence_6,sequence_3,((sequence_2,sequence_5),(sequence_4,sequence_1 #1)));`

I'll just keep running 4.9j for now, but would be great to know if there's something that I'm missing here!

Thanks!

Axel

**Comment by sabifo4** [comment]
Hi Axel, 

I believe you are missing the PHYLIP header in the tree file. In your case, you have 6 sequences and 1 tree file, and thus the PHYLIP header should be the following:

```text
6 1
```

All the details with regards to the input data format can be found [on the PAML Wiki](https://github.com/abacus-gene/paml/wiki/Data-formatting). You will also find an example on how to work with CODEML in our latest protocol for beginners ([Álvarez-Carretero et al. 2023](https://doi.org/10.1093/molbev/msad041)) as well as in [the corresponding GitHub repository for the examples described in the paper](https://github.com/abacus-gene/paml-tutorial/tree/main/positive-selection).

Please let me know if that was the problem so I can close this issue.

Cheers!

**Comment by axeljen** [comment]
Yup that did the trick, thanks for the quick response!

Cheers
