### ISSUE TITLE
High Sequence Count (>2000) Causes Extended Computation Time in ConDEML

### ISSUE THREAD

**Issue by wlhCNU** [abacus-gene/paml#42]
Hi,
I extend my heartfelt gratitude for providing such outstanding software. I analysised with over 2000 sequences and performed site model, branch model, and branch-site model analyses using condeml. The computation has been running for a week, and I've observed that it operates as a single thread on Linux.
I wanted to inquire if condeml supports multi-threading functionality, as enabling this feature could significantly reduce the computation time, especially when dealing with a large number of sequences. 
 Thanks.

**Comment by sabifo4** [comment]
Hi there,

Thanks for your message! Unfortunately, PAML programs do not support this feature at the moment.

All the best,
S.
