### ISSUE TITLE
How to identify positive selected sites using Branch site model

### ISSUE THREAD

**Issue by aaannaw** [abacus-gene/paml#48]
Hello, Professor
I am running /data/01/user157/software/paml4.8/bin/codeml test.ctl to identify positive selected genes.  I can see the positive selected sites in the foreground Hgl clade, which is marked by blue box in the picture. However the codeml output show no positive selected sites 
for the gene. 
![image](https://github.com/abacus-gene/paml/assets/109299053/e8656b15-10ea-40fc-98f4-3b189dc999c8)
![image](https://github.com/abacus-gene/paml/assets/109299053/17d2fe50-3863-49c6-8d07-e80694b3a88e)
I have uploaded these input  file: sequence file (cds.paml), ctl file (branch-site.Hgl.nofix.ctl), tree file (tree.Hgl)  and the output file (branch-site.Hgl.nofix.mlc) for your viewing. I could not actually understand the BEB test, could you give me any suggestions?
Thank you very much!
[branch-site.Hgl.nofix.ctl.txt](https://github.com/abacus-gene/paml/files/15452439/branch-site.Hgl.nofix.ctl.txt)
[branch-site.Hgl.nofix.mlc.txt](https://github.com/abacus-gene/paml/files/15452441/branch-site.Hgl.nofix.mlc.txt)
[cds.paml.txt](https://github.com/abacus-gene/paml/files/15452442/cds.paml.txt)
[tree.Hgl.txt](https://github.com/abacus-gene/paml/files/15452459/tree.Hgl.txt)

**Comment by sabifo4** [comment]
Hi there!

As explained in [the PAML Wiki](https://github.com/abacus-gene/paml/wiki), the GitHub repository is aimed at issues related to technical issues. For non-technical questions and debates, there is a [PAML discussion group](https://groups.google.com/g/pamlsoftware) that people are encouraged to use -- you may even find that similar questions to yours have been posted there (e.g., use the search bar and use key words to find the answer to your question). While this issue should have been posted on the PAML discussion group, please find below some guidelines to answer your question.

The BEB test is described in [Yang and Nielsen (2005)](https://academic.oup.com/mbe/article/22/4/1107/1083468). We also explained how to run tests for positive selection and showed how to interpret the BEB results on our latest protocol ([Álvarez-Carretero et al., 2023](https://doi.org/10.1093/molbev/msad041)). You can also find a reproducible tutorial on our [`positive-selection`](https://github.com/abacus-gene/paml-tutorial/tree/main/positive-selection) repository. Hope these resources help you better understand how to interpret the BEB results! 

All the best,
Sandy

P.S.: For further related non-technical issues, please use the [PAML discussion group](https://groups.google.com/g/pamlsoftware) :)
