### ISSUE TITLE
MCMCTREE in paml version 4.10.7, June 2023 Reading main tree.  error: raise NS?(base)

### ISSUE THREAD

**Issue by wenhaoli-wenhaoli** [abacus-gene/paml#51]
After constructing a Maximum Likelihood (ML) tree using the amino acid sequences of 16 single-copy genes from 808 microbial genomes, I conducted a molecular clock analysis using this ML tree and the amino acid alignment file. However, when using the complete dataset, the following error occurred, while using data from 500 genomes allowed the process to run normally.

MCMCTREE in paml version 4.10.7, June 2023

Reading options from mcmctree.ctl..
finetune is deprecated now.

Reading main tree.

error: raise NS?(base)

How can I solve this problem? Additionally, which parameters in the mcmctree.ctl file should I pay attention to? I have seen some articles using the WAG protein substitution model, but it seems unavailable in this version. Here is my mcmctree.ctl file.
[mcmctree.txt](https://github.com/user-attachments/files/16383210/mcmctree.txt)

**Comment by sabifo4** [comment]
Hi there,

As explained in [the PAML Wiki](https://github.com/abacus-gene/paml/wiki), the GitHub repository is aimed at issues related to technical issues. For non-technical questions and debates, there is a [PAML discussion group](https://groups.google.com/g/pamlsoftware) that people are encouraged to use -- you may even find that similar questions to yours have been posted there (e.g., use the search bar and use key words to find the answer to your question). While this issue should have been posted on the PAML discussion group, please find below some guidelines to answer your question.

Various questions regarding the `raise NS?` have been posted on the PAML discussion group; [you may want to take a look at this thread of messages](https://groups.google.com/g/pamlsoftware/c/NCnUHmNC9D0/m/lnmAPkp0AQAJ) where I also included a picture showing how to sort this problem. With regards to the options that should be included in the control file, you [should read the PAML documentation](https://github.com/abacus-gene/paml/blob/master/doc/pamlDOC.pdf), where everything is detailed under the section referring to analyses with `MCMCtree`. I also have [some examples and guidelines in one of my GitHub repositories](https://github.com/sabifo4/mammals_dating/tree/main/01_SeqBayes_S1/02_MCMCtree) which you may want to check.

Hope this helps!
