### ISSUE TITLE
Some thing go wrong when species ID is/are numeric.

### ISSUE THREAD

**Issue by xiekunwhy** [abacus-gene/paml#9]
Hi,

When species name is/are numeric(larger than species number, >122 in my case), mcmctree can not run normally, it seems that only v4.7a/b can handle this situation.
For example
122 1
((((((((((((((((38,110),80),40),(((1,44),10),36)),(((((116,((84,85),86)),30),Hic),107),87)),((122,108),88)),(120,125)),121),((119,123),124)),((66,79),55)),81),22),(((((((((39,(((11,98),12),((47,(62,70)),48))),43),((((103,109),74),(32,100)),(7,95))),3),(15,19)),(46,56)),((((20,75),(35,37)),41),61)),93),(((((((((((((((54,52),53),33),17),50),(60,94)),((((59,(64,(105,9))),101),(2,63)),(34,(71,90)))),6),(((((((4,72),5),31),29),102),27),89)),106),49),(57,16)),(104,8)),23),28))),((82,99),97)),((((51,(((((((((58,112),76),((18,77),67)),69),(113,114)),(118,13)),111),92),83)),((21,24),26)),91),((25,((42,73),(68,78))),96))),45)'>0.0688<0.2096';

mcmctree mcmctree100w.ctl
MCMCTREE in paml version 4.9j, February 2020

Reading options from mcmctree100w.ctl..
finetune is deprecated now.
Reading master tree.

Seq/species #1 (Hic) occurs more than once in the tree

**and when I change Hic to 130**

MCMCTREE in paml version 4.9j, February 2020

Reading options from mcmctree100w.ctl..
finetune is deprecated now.
Reading master tree.

Seq/species #1 (130) occurs more than once in the tree

**and when I add R(or any other letters) before each species ID, every thing was normal.**

So I think this is a bug(except v4.7a/b).

Best,
Kun

**Comment by ziheng-yang** [comment]
please avoid using numbers as sequence names.
please post questions at the paml discussion site.
ziheng
